# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rService.proto\"A\n\x06\x43reate\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x16\n\x0enum_partitions\x18\x02 \x01(\x05\x12\x0c\n\x04size\x18\x03 \x01(\x05\"\x8d\x01\n\x0e\x43reateResponse\x12\x33\n\npartitions\x18\x01 \x03(\x0b\x32\x1f.CreateResponse.PartitionsEntry\x12\x13\n\x0bstatus_code\x18\x02 \x01(\x05\x1a\x31\n\x0fPartitionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\x37\n\x08NameNode\x12+\n\rCreateRequest\x12\x07.Create\x1a\x0f.CreateResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CREATERESPONSE_PARTITIONSENTRY']._options = None
  _globals['_CREATERESPONSE_PARTITIONSENTRY']._serialized_options = b'8\001'
  _globals['_CREATE']._serialized_start=17
  _globals['_CREATE']._serialized_end=82
  _globals['_CREATERESPONSE']._serialized_start=85
  _globals['_CREATERESPONSE']._serialized_end=226
  _globals['_CREATERESPONSE_PARTITIONSENTRY']._serialized_start=177
  _globals['_CREATERESPONSE_PARTITIONSENTRY']._serialized_end=226
  _globals['_NAMENODE']._serialized_start=228
  _globals['_NAMENODE']._serialized_end=283
# @@protoc_insertion_point(module_scope)
