name: Docker Image CI Cliente

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Copy Project Code
        uses: actions/checkout@v3

      - name: Docker login
        env:
          DOCKER_USER: ${{secrets.DOCKERHUB_USER}}
          DOCKER_PASS: ${{secrets.DOCKERHUB_PASS}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS

      - name: Build the Docker Image
        run: |
          cd Cliente
          docker build . --tag msosav/ccs-file-system-cliente:latest

      - name: Docker Push
        run: docker push msosav/ccs-file-system-cliente
